### ISSUE TITLE
Polmine.pl's pool detection URL is broken

### ISSUE THREAD

**Issue by Eveiv** [bitpay/insight-ui#401]
I'm at a loss as to why this pool's URL in the block view is broken. The outgoing link in the web interface decodes to "https://polmine.pl/%E2%80%8E" but the strings file doesn't contain those characters at all. Is there some sort of encoding problem I'm not aware of? 

Relevant line: 
https://github.com/bitpay/insight/blob/master/etc/minersPoolStrings.json#L138

Example block: 
http://live.bitcore.io/block/00000000000000004dc7fdb04bdd5aa03f7cb0abf2792fcca8761f0c2dd1c216

**Comment by braydonf** [comment]
Looks like this is still an issue: https://insight.bitpay.com/block/00000000000000004dc7fdb04bdd5aa03f7cb0abf2792fcca8761f0c2dd1c216
