### ISSUE TITLE
post a torrent of a pre-indexed insight database to avoid sync time

### ISSUE THREAD

**Issue by maraoz** [bitpay/insight-ui#462]
Suggested by @jgarzik

**Comment by dabura667** [comment]
+1

**Comment by phutchins** [comment]
+1 for this...

**Comment by braydonf** [comment]
Mostly relevant for https://github.com/bitpay/bitcore-node now, and could be relevant for running on devices without much CPU. However with headers first sync, it may not be that helpful in general?

**Comment by braydonf** [comment]
Indexing times are around the same time as the initial block download, and around 12-24 hours, bandwidth largely the bottleneck.
