### ISSUE TITLE
Incorrect balance

### ISSUE THREAD

**Issue by ouziel-slama** [bitpay/insight-ui#553]
For this address the final balance and unconfirmed balance are incorrect:
https://insight.bitpay.com/api/addr/1HiBGx4e6VCA1K4cxNQctUuZJDt4f2unyQ
https://blockchain.info/address/1HiBGx4e6VCA1K4cxNQctUuZJDt4f2unyQ
the problem seems to come from multisig outputs.

**Comment by braydonf** [comment]
Similar issue as: https://github.com/bitpay/insight-api/issues/370
