### ISSUE TITLE
issues installing insight 

### ISSUE THREAD

**Issue by daftpunk80** [bitpay/insight-ui#575]
ran npm install on the command line and keep getting the following issue, can anyone help?
![insight_install_issue](https://cloud.githubusercontent.com/assets/9435623/4837103/f09455ec-5fcf-11e4-9feb-98cbacfd8377.png)

**Comment by Klakurka** [comment]
I'm also unable to install base58-native... any suggestions? This is on Windows 7 x64.

![fail](https://cloud.githubusercontent.com/assets/4713204/6548393/44881342-c5b4-11e4-950c-73eed2c26423.png)

**Comment by braydonf** [comment]
Outdated
