### ISSUE TITLE
How to change the browser port from 3000 to 80

### ISSUE THREAD

**Issue by terrylai** [bitpay/insight-ui#576]
Hello all, 

I tried to change the port setting in file node_modules/insight-bitcore-api/config/config.js

The change is just to change the following:

port = '3000';

to

port = '80';

However, after changing and run npm start, I get the following message:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1023:19)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at Object.<anonymous> (/home/de/insight/node_modules/insight-bitcore-api/insight.js:156:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

npm ERR! insight-bitcore@0.2.5 start: `INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the insight-bitcore@0.2.5 start script.
npm ERR! This is most likely a problem with the insight-bitcore package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api
npm ERR! You can get their info via:
npm ERR!     npm owner ls insight-bitcore
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.15.4-x86_64-linode45
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /home/de/insight
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/de/insight/npm-debug.log
npm ERR! not ok code 0
de@li113-161:~/insight$ 
 
Do anyone know how to solve it?

**Comment by braydonf** [comment]
With latest version, you can update port in `bitcore-node.json`
