### ISSUE TITLE
Try to get it work for paycoin

### ISSUE THREAD

**Issue by ChristianGrieger** [bitpay/insight-ui#592]
Hey there,
so i spend hours now to try to get this nice thing working for a new coin called paycoin but i am not able to get it to work. So it seems never to connect right.
Plese contact me okay? I am also willing to pay for it to set it up.
Thanks! 
My Mail: info@bitcoinproject.net

**Comment by genecyber** [comment]
Edit network.js in the bitcore module (and in /lib/bitcore.js 

Update genesis and merkle 
For the genesis block, split actual hash into a string of hex pairs and flip each pair and also reverse the order of the pairs like this: 

00 01 02 03 becomes
30 20 10 00

**Comment by ChristianGrieger** [comment]
So i had many people now Try to get this coin work and no one was able to. The problem is that paycoin xpy has another timestamp Format. Also we was able To get the Genesis Block information, but was not able To find the Magic number of that Coin. I hope someone could set this up for me :( so if You are able To do so genecyber please add me On Skype. The Name is ticer89. Thank you!
