### ISSUE TITLE
Insight not accepting valid transactions

### ISSUE THREAD

**Issue by prusnak** [bitpay/insight-ui#599]
We are experimenting with broadcasting transactions from our wallet MyTrezor.com via insight API, but serveral users reported they their transactions are refused by the Insight server. We suspect there is a bug in your code, because these transactions are valid (and accepted by network).

Typical error message from Insight:

Server returned:
{"data":null,"status":0,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"https://insight.bitpay.com/api/tx/send","data":{"rawtx":"0100000001b9c76648e7bd586282b91f78a0b6dd90d0063b346ed85dc782aa0dde2365600b000000006b483045022100e68404226514b83e98b4488a53c31b471e81b327d820d3692a15fdbc5b8cb66902206a095e9475e671cc892049fc0c15df793af81ce7b1bef1c51d562f5175331403012102828e1e1ecdf136e147f09336f3ae9b01fb5e7fdd6977becfb91934278ae0a586ffffffff02e2159cc9040000001976a914a0dd0000dea425a52ee29345ac84b8390cbb18af88ac0065cd1d000000001976a91403bde9dce2ce6c87ccbadffc8b8ae27bc5168a9288ac00000000"},"headers":{"Accept":"application/json,
text/plain,
*/*","Content-Type":"application/json;charset=utf-8"}},"statusText":""}

More examples of refused transactions (raw):
01000000014dcf396b434a05e088f4bd6f4751e038c6be0b9d15b7c651917ba2b346f22b7a010000006b483045022100edb3cdf5f0fe84f20b9f7ffb81770bc67737b6d7ef9658812131c6168ecd45dc022041177ea81e1e1c3178ee11f0b29f98926287f7d13666729d8e1b7d02355c5a4b01210350977566cb14eef6b7dbfe1dc99c077be523cdbeb4a1f667a2726647e1913346ffffffff0180380100000000001976a914aee527eb9280c04955c17f2f8001ed651b5b4ab088ac00000000

0100000001d8bac4147a6ca37e74e9a3a7bee68a56f1d3c42e31bfbb389d505f9581ddff00010000006a47304402201e812fd3fc39fb35edaa89034fffc7704d882ccb75e29d6215223e40cc769c4e022004b358dcbf7fc57faf50e28eb6f491b3abf4fe956ce284b18a630c9fa586a32a012103b170170114764fa160b32c0ca29e4d531665dd6f6df741d67d5acde70e21bfd2ffffffff025009e908000000001976a914534d4f9a06c4ea284729bfe0e5224a51684aa40888ac20a10700000000001976a91419efda9f0191e9f48c3e55dd5e819d598486382488ac00000000

**Comment by maraoz** [comment]
Are you getting literally:
```
{"data":null,"status":0,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"https://insight.bitpay.com/api/tx/send","data":{"rawtx":"0100000001b9c76648e7bd586282b91f78a0b6dd90d0063b346ed85dc782aa0dde2365600b000000006b483045022100e68404226514b83e98b4488a53c31b471e81b327d820d3692a15fdbc5b8cb66902206a095e9475e671cc892049fc0c15df793af81ce7b1bef1c51d562f5175331403012102828e1e1ecdf136e147f09336f3ae9b01fb5e7fdd6977becfb91934278ae0a586ffffffff02e2159cc9040000001976a914a0dd0000dea425a52ee29345ac84b8390cbb18af88ac0065cd1d000000001976a91403bde9dce2ce6c87ccbadffc8b8ae27bc5168a9288ac00000000"},"headers":{"Accept":"application/json,
text/plain,
/","Content-Type":"application/json;charset=utf-8"}},"statusText":""}
```
as a response from insight, or is the response empty, as suggested by `"transformResponse":[null]`? How are you interacting with the API? (library, tool, language?)

**Comment by prusnak** [comment]
CC @jpochyla @runn1ng @slush0

**Comment by matiu** [comment]
Copays only proxies the rawTX to the paired bitcoind instance, if the transaction is refused is probably because bitcoind refuse it. Are you using the insight.bitpay.com? Or your own server?

**Comment by prusnak** [comment]
insight.bitpay.com

**Comment by braydonf** [comment]
Getting these errors now:
- #1 transaction already in block chain. Code:-27
- #2 Missing inputs. Code:-25

Let us know if there are still any issues. @matiu is correct, the raw tx is directly passed to bitcoind:
- https://github.com/bitpay/insight-api/blob/master/lib/transactions.js#L288-L298
- https://github.com/bitpay/bitcore-node/blob/master/lib/services/bitcoind.js#L1760-L1783
