### ISSUE TITLE
How to get block times?

### ISSUE THREAD

**Issue by GreydonIselmoe** [bitpay/insight-ui#613]
Sorry for creating multiple issues.

I can't seem to figure out how to get times block specific blocks, I can see in /insight/public/views/index.html that insight is using AngularJS and calling {{humanSince(b.time)}}, but when I try and create another instance for <class="fader" data-ng-repeat='b in blocks'> and try and get {{humanSince(b.time)}} it keeps returning "a few seconds ago".

My goal is to create an array of block times for the last 10, 50, 100 blocks which creates an average block time with the given timestamps. Any thoughts?

**Comment by braydonf** [comment]
I think this may be more related to insight-api, please see docs there: https://github.com/bitpay/insight-api#block
