### ISSUE TITLE
insight  and Blackcoin (POS/POW) coin

### ISSUE THREAD

**Issue by coingeek** [bitpay/insight-ui#619]
How we can make the insight works with Blackcoin??

can anyone help in this issue.

**Comment by AkiraTakizawa** [comment]
You will have to modify several files from bitcore, insight-api and insight to make it understand BLK. I'm porting it to Mineralscoin at the moment, and it's not completely done yet. It's not much, but check my repos for an idea. 

BLK probably requires you to replace some of the SHA256 functions by Scrypt functions? If Litecoin oe another Scrypt altcoin runs insight, check their repositories too. It might be very useful to get an idea of what needs to be changed for Blackcoin.

Success!

**Comment by braydonf** [comment]
There are several things that would need to be changed, starting with indexes similar to: https://github.com/bitpay/bitcoin/tree/0.12-bitcore
