### ISSUE TITLE
one CPU core goes to 100%  after few minutes than Insight hangs/crashs

### ISSUE THREAD

**Issue by mmitech** [bitpay/insight-ui#685]
As mentioned in the title, one insight instance (1 CPU core) goes to 100% and Insight become unresponsive until I kill it and restart it. 

![2015-11-10 14_21_20-fotografije](https://cloud.githubusercontent.com/assets/4456920/11063816/6158d62e-87b9-11e5-8d4e-38ad58a22161.png)

**Comment by braydonf** [comment]
This looks like it's using an older version. The latest version is significantly different, so this issue may not be relevant.

**Comment by mmitech** [comment]
Hello, 

I checked the production tag when cloning, insight-API version v0.2.18 and this is the production version as well.

I tried to deploy the latest version but the bitcore-lib always fail to compile with this error:

        /usr/local/lib/node_modules/bitcore-node/libbitcoind
       ./autogen.sh
       configure.ac:25: installing 'build-aux/compile'
       configure.ac:5: installing 'build-aux/config.guess'
       configure.ac:5: installing 'build-aux/config.sub'
       configure.ac:9: installing 'build-aux/install-sh'
       configure.ac:9: installing 'build-aux/missing'
       Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
       Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
       Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
       Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
       Makefile.am:3:   its definition is in aclocal's search path.
       Makefile.am: installing 'build-aux/depcomp'
       parallel-tests: installing 'build-aux/test-driver'
       autoreconf: automake failed with exit status: 1
       npm ERR! Linux 3.19.0-33-generic
       npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "bitcore-node@latest"
       npm ERR! node v0.10.40
       npm ERR! npm  v2.14.9
       npm ERR! code ELIFECYCLE

       npm ERR! bitcore-node@1.0.0 install: `./bin/install`
       npm ERR! Exit status 255
       npm ERR!
       npm ERR! Failed at the bitcore-node@1.0.0 install script './bin/install'.
       npm ERR! This is most likely a problem with the bitcore-node package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     ./bin/install
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls bitcore-node
       npm ERR! There is likely additional logging output above.
     
I can't get Copay to work with insight being unstable.

**Comment by bitcoinsSG** [comment]
I suspect your culprit is here, (haven't recreated the error but recalling from memory)
      **npm ERR! node v0.10.40**
I had a similar error that was resolved on machines that had node.js v 0.12.x & 4.2.x, i recommend trying to update your nodejs and trying again.

**Comment by braydonf** [comment]
Yep, bitcore-node currently supports Node.js v0.12 and Node.js v4.2

**Comment by braydonf** [comment]
More details here: https://bitcore.io/guides/full-node

**Comment by mmitech** [comment]
Will try it over weekend, and report.

**Comment by mmitech** [comment]
Issue solved, problem caused by the coin daemon.
