### ISSUE TITLE
 Incoherence in levelDB detected: Input spent not registered

### ISSUE THREAD

**Issue by mmitech** [bitpay/insight-ui#693]
Under Latest transactions I see the incoming transaction with 0 value and when I click on it I get the error "transaction not found".
Additionally if I copy the txid from my wallet and paste it in insight, I can see the unconfirmed transaction with the input error " Incoherence in levelDB detected: Input spent not registered", this error will disappear when I have at least one confirmation, I do have txindex=1, I can lookup transactions in my daemon and I get all info even for the non-confirmed ones.

what could be wrong ?

**Comment by matiu** [comment]
Are you using the "old" insight-api?

Please note that we are recommending to use bitcore instead of insight-api.
Check the updated readme at: https://github.com/bitpay/insight-api

On Mon, Nov 16, 2015 at 6:58 AM, Mourad Ilyes Mlik <notifications@github.com
> wrote:

> Under Latest transactions I see the incoming transaction with 0 value and
> when I click on it I get the error "transaction not found".
> Additionally if I copy the txid from my wallet and paste it in insight, I
> can see the unconfirmed transaction with the input error " Incoherence in
> levelDB detected: Input spent not registered", this error will disappear
> when I have at least one confirmation, I do have txindex=1, I can lookup
> transactions in my daemon and I get all info even for the non-confirmed
> ones.
>
> what could be wrong ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/insight/issues/693>.
>



-- 
BitPay.com

**Comment by mmitech** [comment]
I am using an older version, I am aware of bitcore because I just started (this weekend) using it for my bitcoin nodes, but this one I am trying to use for an alt and I didn't try to import bitcore yet.

**Comment by braydonf** [comment]
Outdated
