### ISSUE TITLE
QR scanner error on mobile.

### ISSUE THREAD

**Issue by cnu1439** [bitpay/insight-ui#707]
I'm getting "Couldn't find enough finder patters" error very frequently while scanning for bitcoin address.

![screenshot_20160512-144157](https://cloud.githubusercontent.com/assets/5406199/15209713/4f24ab36-1850-11e6-8dd7-dd9cfbf937f3.png)

**Comment by aciddude** [comment]
You just need to use a higher res image or take a better photo.
