### ISSUE TITLE
Money

### ISSUE THREAD

**Issue by mtrojan21** [bitpay/insight-ui#712]
When will I get that money

**Comment by gabegattis** [comment]
@mtrojan21 Can you explain this more thoroughly or are you just trolling?

**Comment by mtrojan21** [comment]
I don't seem to be getting any payments

**Comment by gabegattis** [comment]
Are you not getting notifications for transactions in Copay? We need more info.

**Comment by mtrojan21** [comment]
I'm not getting nothing

**Comment by gabegattis** [comment]
Anything else? Screenshots, version numbers, error messages?

**Comment by mtrojan21** [comment]
I've shared an item with you:

Advertising Summary
http://docs.google.com/spreadsheets/d/1AEfPSqiW-1ev2vVhKGjlgi6J46XUcWMbmlVUc7uHF8k/edit?usp=sharing&invite=CILtvJUK&ts=570ce283

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by mtrojan21** [comment]
Hi bitpay/insight-ui,

I'd like to add you to my professional network on LinkedIn.

- Matthew

Confirm that you know Matthew: https://www.linkedin.com/e/v2?e=0-io7orj3g-fi&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=rJg7kH-Y&invitationId=6137367987470036992








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-io7orj3g-fi&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEcuhs8NvhQxAAAAVSxPz2PPbp8L8l6tnZzFl9Mk4N_LATE-j_kLF_mwSVkUdUh4ACxIP8w7XMpheZqzwoPGQrI6OFcXtgJvd8Jb2QkPKfA93Gsd8ZSKUlmIv8iX9Zmzze4YC7rvme9LUX10Ffijww0AEiuJocYo1NsUIQ1l1V8a2sRh9cj3tvX04PjoE53KW9U&eid=0-io7orj3g-fi


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-io7orj3g-fi&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by mtrojan21** [comment]
Matthew Trojan would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=4cjcmw-iooa497l-tx&t=ssuw&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=rJg7kH-Y&invitationId=6137367987470036992

View Matthew Trojan&#39;s profile: https://www.linkedin.com/e/v2?e=4cjcmw-iooa497l-tx&t=ssuw&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=rJg7kH-Y&invitationId=6137367987470036992





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=4cjcmw-iooa497l-tx&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=4cjcmw-iooa497l-tx&loid=AQEcROvd_mfcqwAAAVTuUbppt0mbt4zYsV-NbYZtgcn5OXaQ5hVPugVUflPIWXAgKSJVr4AwUKbzIcWTivtodaPPqLro81vVOChe9l1fPs2ozTKwOAIskpoOrYKe42dwW_OsvjofGveSsv4Y2u4j516dnqc7gFzL1k8u1DWSK0LED9HL9AtOn0TzhohUS9J-0whl

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=4cjcmw-iooa497l-tx&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
