### ISSUE TITLE
API lists wrong TXID under UTXO

### ISSUE THREAD

**Issue by vupeter** [bitpay/insight-ui#715]
Example:
https://insight.bitpay.com/api/addr/12VbzMm5Kh4Q2rgVTnYJzsRU9fsYj6H2KZ/utxo
`[{"address":"12VbzMm5Kh4Q2rgVTnYJzsRU9fsYj6H2KZ","txid":"90b8310c95c830d28fd10c94dd813003c72cc2ed13cac786fb5ee4a583e01d6b","vout":1,"ts":1462947073,"scriptPubKey":"76a9141060fae162dbddaf41e0fde85419c318de49672188ac","amount":0.00001,"confirmationsFromCache":false}]`

The txid listed there does not exist, and the txid of the actual UTXO at the time is:
d1824a6364031ae84a8b6a0f28e31b1313f4fffe759788d7b42b59cf3b8e4dbc

**Comment by braydonf** [comment]
This has likely outdated now.
