### ISSUE TITLE
Rate limit exceeded: ERROR

### ISSUE THREAD

**Issue by masureshho** [bitpay/insight-ui#720]
I was writing some tests for my app, And i got this message, {"status":429,"error":"Rate limit exceeded"}
I am not being able to get UTXO's can you please show me the solution.

**Comment by matiu** [comment]
Public Insight server has a limit of request per unit of time to protect the server from abuse.

If you plan need to do a high number of requests, you need to install your own server.

**Comment by rgenito** [comment]
does anyone know the rate limit? or how to find the rate limit?

**Comment by usab** [comment]
I have my own insight server. How can I increase this value?
Error message is as follows:


error | "Rate limit exceeded"
-- | --

**Comment by usab** [comment]
Got it!

Just add this in bitcore-node.json:

  "servicesConfig": {
    "insight-api": {
      "disableRateLimiter": true
    }
  }

**Comment by winteraz** [comment]
For some reasons it's not working for me. I still get the ` Rate limit exceeded` error. Any idea why ???

```
$ cat bitcore-node.json
{
  "network": "livenet",
  "port": 3001,
  "services": [
    "bitcoind",
    "insight-api",
    "web"
  ],
  "servicesConfig": {
	  "insight-api": {
	"disableRatelimiter": true
   },
   "bitcoind": {
      "spawn": {
        "datadir": "./data",
        "exec": "/home/azureuser/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/bitcore-node/bin/bitcoind"
      }
    }
  }

```
