### ISSUE TITLE
.script/download failure

### ISSUE THREAD

**Issue by GeRikz** [bitpay/insight-ui#734]
> bitcore-node@3.1.2 preinstall /root/.nvm/versions/node/v4.5.0/lib/node_modules/bitcore-node
> ./scripts/download

./scripts/download: line 30: cd: /root/.nvm/versions/node/v4.5.0/lib/node_modules/bitcore-node/scripts/../bin: Permission denied
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/root/.nvm/versions/node/v4.5.0/bin/node" "/root/.nvm/versions/node/v4.5.0/bin/npm" "install" "-g" "bitcore-node"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! bitcore-node@3.1.2 preinstall: `./scripts/download`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitcore-node@3.1.2 preinstall script './scripts/download'.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/download
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bitcore-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by braydonf** [comment]
> **Note**: Do not run this command with sudo or with root privileges as this will lead to [permission issues](https://docs.npmjs.com/misc/scripts#user). 

https://bitcore.io/guides/full-node#install-bitcore
