### ISSUE TITLE
Error! Can't connect to bitcoind to get live updates from the p2p network. (Tried connecting to bitcoind at : and failed.)

### ISSUE THREAD

**Issue by manuel-di-iorio** [bitpay/insight-ui#743]
https://insight.bitpay.com

**Comment by manuel-di-iorio** [comment]
It is working now.

**Comment by gabegattis** [comment]
We are investigating this issue. Our current hypothesis is related to Cloudflare killing our websockets connections. @kleetus

**Comment by manuel-di-iorio** [comment]
Is this issue related only to me ?
In fact, I saw the previous days the error "429 API Rate Limit excedeed". Actually, now it's working the website. 

If this is the situation, probably there should be a better message instead of "can't connect" :)

**Comment by gabegattis** [comment]
The "Can't connect to bitcoind to get live updates from the p2p network." error is not related to the 429 rate limit error.

The can't connect error is a general one, not specific to you.

The 429 error is specific to you though. It means that you were hitting our api too rapidly, so we limited your requests.

**Comment by manuel-di-iorio** [comment]
Oh ok thanks for the notice!
