### ISSUE TITLE
Option to serve insight ui from /

### ISSUE THREAD

**Issue by hkparker** [bitpay/insight-ui#745]
It would be great to be able to host a public instance of bitcore with insight, and be able to host insight on the root path via a configuration option, as opposed to /insight.  I'll look into patching this into my install.

**Comment by Fyah112** [comment]
Also would like to see a way to do this.

**Comment by sergeym0** [comment]
You can add this into your **bitcore-node.json**:
```json
  "servicesConfig": {
    "insight-ui": {
      "routePrefix": ""
    }
  }
```

**Comment by hkparker** [comment]
Sweet, thanks!  I just couldn't find this is any documentation, and I'm not really a node guy.  Lookin' pretty great now.
