### ISSUE TITLE
How to use insight for Altcoins?

### ISSUE THREAD

**Issue by globaltoken** [bitpay/insight-ui#754]
Hey,

If I use insight for Altcoins i got every time a Sync could not loaded [obj obj] Error?
It shows correct Block Amount, but there is no Live Transaction or any Block in Frontend.

Where is this Possible to fix that?
What have to be replaced in which files to use this with an Altcoin?

Thanks for your help!

**Comment by xlp0rk0lx** [comment]
Some news ? (:

**Comment by anggaand123** [comment]
can you guide for instalation altcoin insight ?? @globaltoken

**Comment by anggaand123** [comment]
is it must install of 3 this ???
bitcoincore
bitcoin insight api
and then insight frontend ???

**Comment by globaltoken** [comment]
@anggaand123 You need to edit each dependency.
I used the old Source Code with Insight + Core + Api.

It was easier.
The new Code need more things to be changed, but I didn't changed them yet.

**Comment by anggaand123** [comment]
Can you be more detailed, what files should be changed
also what version of 3 them please
@globaltoken

**Comment by globaltoken** [comment]
@anggaand123 You need to change everything like Coin Supply, genesis, block time and so on. Buddy I cannot give you detailed answer it's already about 10 months ago as I changed it.

**Comment by ChristianGrieger** [comment]
A correct old version of Insight + some modifications is the easiest way :P at least if its a BTC forked coin. Else learn to modify Bitcore + lib and get it managed to run (not easy, at least for me)
