### ISSUE TITLE
transation not fund???

### ISSUE THREAD

**Issue by DAVIFONT** [bitpay/insight-ui#757]
I released the transation, but not fund???? the id transation is https://insight.bitpay.com/tx/cf858737c23681cc507e4b05ebb4cddb1ec0050433a4dbbcb9f1cc6d5ce9da3a

Does insight need to solve this problem, or are they applying scams ???

**Comment by RobertBaron** [comment]
Hi @DAVIFONT,

So the insight-ui explorer is not able to find the transaction for whatever reason,  but that doesn't mean that it is any sort of scam..
There are plenty of block explorers where you can look for your transaction for example:
https://tradeblock.com/bitcoin/tx/cf858737c23681cc507e4b05ebb4cddb1ec0050433a4dbbcb9f1cc6d5ce9da3a
Transaction **exists and is valid** , looking at the Fee/size it might take a couple of days to get confirmations.

**Comment by slimshaday** [comment]
I released the transation, but not fund???? the id transation is 
https://insight.bitpay.com/tx/31805182736652ba7ebfe6f1dd647b8c63a724664147bfbea1a4b6c2b5d0e0a9
