### ISSUE TITLE
Transfer deuscoin to android wallet app is missing

### ISSUE THREAD

**Issue by ardize** [bitpay/insight-ui#758]
3 days ago i'm transfer 1 deuscoin from deuscoin web (deuscoin.org) to my wallet, but deuscoin never confirm, and now my transaction hash cannot found, my 1 deuscoin has been missing, plaease fix

**Comment by BitLox** [comment]
Hey, you are commenting on the original source software, what you are looking for is the fork for deuscoin.

**Comment by eastain89** [comment]
I cannot transfer out my deuscoin to svd,how and when did you can update the problem?is that any method to do,because i had try to sending deus to svd it is still got error. Please fix it,because we use the apps as our main wallet.

**Comment by gabegattis** [comment]
This project does not support deuscoin. You are probably looking for a fork of this project.

closing
