### ISSUE TITLE
How to Run Insight with Apache?

### ISSUE THREAD

**Issue by globaltoken** [bitpay/insight-ui#762]
How can I run Insight with Apache, I mean instead of using this IP:PORT ?
How can I disable the Port and just use the Domain without Port?

Thanks,

**Comment by RobertBaron** [comment]
Hi @globaltoken,

That depends on how you want to setup your app, and the deployment process you want.
Usually for apache, users setup a proxy reverse/proxy pass between your app and the server.

Here you can find a detailed guide for it: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04
* previous link uses a Nginx server. but deployment is very similar.

A much more simpler one 
http://blog.podrezo.com/making-node-js-work-with-apache/

**Comment by globaltoken** [comment]
@RobertBaron Thanks a lot buddy!

It's working now, great!

Thanks again for your help :)
