### ISSUE TITLE
transfer not done 

### ISSUE THREAD

**Issue by jmerino2203** [bitpay/insight-ui#773]
Good evening, please request to ensure that the transaction is confirmed because it is not appear , attached link of hash 

https://insight.bitpay.com/tx/0d38126439304d53483c467b7b953ba5bb814fe78e47400fb175ac2921345ee9

**Comment by tuandoan1799** [comment]
Dear
I have a digibyte account on google. Transaction on 1,060,360 dgb account on 5/5/2017. But I do move to another account not. And it's display is locked waiting for confirmation. Thanks admin for help
https://digiexplorer.info/tx/b2a4612fddd0604dff7857b9624755e01f654b4f818d98c60f08e87761910701
